In [1]:
import numpy as np

In [16]:
# def add_dim(x, data = {"depth":0}):
#     if x.shape[0]>0:
#         data["depth"]+=1
#         return np.array([add_dim(x[1:], data) for _ in range(x[0])])
#     else:
#         return Node(0)
        

In [250]:
np.linalg.norm([1, 1, 1])

1.7320508075688772

In [901]:
class Node():
    def __init__(self, lattice, *args):
        self.lattice = lattice
        self.weight   = np.array(args) 
        self.position = np.array(args)
        
    def get_weight(self):
        return self.weight
    
    def get_position(self):
        return self.position
    
    def distance_to(self, vector):
        return self.lattice.distance_function(vector- self.weight)
    
    def __getitem__(self, i):
        return self.position[i]
    
    
class Lattice():
    def __init__(self):
        self.lattice = None
        self.distance_function = np.linalg.norm
             
    def __getitem__(self, position):
        return self.lattice[position]   
        
    
    def distance(self, node_1, node_2):
        return self.distance_function(node_1.weight-node_2.weight)
    
    def get_node_weight(self, position):
        return self[position].get_weight()
    
        
    def get_weight(self):
        f = np.vectorize(lambda node: node.get_weight(), signature='()->(n)')
        return f(self.lattice)
    
    def get_position(self):
        f = np.vectorize(lambda node: node.get_position(), signature='()->(n)')
        return f(self.lattice)
    
    
    
    def relative_distance(self, ref_vector):
        f = np.vectorize(lambda node: node.distance_to(ref_vector))
        return f(self.lattice)
    
    def find_closest_id(self, ref_vector):
        distance_matrix = self.relative_distance(ref_vector)
        return np.unravel_index(distance_matrix.argmin(), distance_matrix.shape)
    
    def find_closest(self, ref_vector):
        return self.lattice[self.find_closest_id(ref_vector)]
    
#     def u_matrix(self):
#         f = np.vectorize(lambda node_1, node_2: self.distance(node_1, node_2))
#         return f(self.lattice, self.lattice)
        

    def train(self, input):
        candidate = self.find_closest(input)
        distance_to_candidate = self.relative_distance(candidate.get_weight())
        print(distance_to_candidate)
        
        for node in self:
            node.update(candidate) #candidate ou input ? Regarder
    # TODO : add an iterable here, to avoid thinking about i, j (, k, ...)
    
    
    def __iter__(self):
        pass
    
    
    
class Lattice_1D(Lattice):
    def __init__(self, list_dim):
        super().__init__()
        self.lattice = np.array([Node(self, i) for i in range(list_dim[0])])
                
    def __iter__(self):
        for i in xrange(self.list_dim[0]):
            yield self.lattice[i]
    
        
class Lattice_2D(Lattice):
    def __init__(self, list_dim):
        super().__init__()
        self.list_dim = list_dim
        self.lattice = np.array([[Node(self, i, j) for j in range(list_dim[1])] 
                                                   for i in range(list_dim[0])])
        
    
    def __iter__(self):
        for i in range(self.list_dim[0]):
            for j in range(self.list_dim[1]):
                yield self.lattice[i][j]

In [902]:
x = np.array([3, 5])

In [903]:
y = Lattice_2D(x)

In [904]:
np.array(y.lattice).shape

(3, 5)

In [905]:
w = y.get_weight()

In [906]:
a = y[1, 0]
b = y[1, 3]

In [907]:
y.distance(a, b)

3.0

In [908]:
y[1, 3].weight

array([1, 3])

In [909]:
y.find_closest(y[1,0].weight+np.array([1, 3]))

In [910]:
y.find_closest_id(y[1,0].weight+np.array([1, 3]))

(2, 3)

In [911]:
y.lattice[y.find_closest_id(y[1,0].weight+np.array([1, 3]))]

In [912]:
y.train(np.array([0.75, 0.75]))

[[1.41421356 1.         1.41421356 2.23606798 3.16227766]
 [1.         0.         1.         2.         3.        ]
 [1.41421356 1.         1.41421356 2.23606798 3.16227766]]


In [913]:
for x in y:
    print(x.position)

[0 0]
[0 1]
[0 2]
[0 3]
[0 4]
[1 0]
[1 1]
[1 2]
[1 3]
[1 4]
[2 0]
[2 1]
[2 2]
[2 3]
[2 4]


In [887]:
x = np.array([3])

In [888]:
y = Lattice_1D(x)

In [889]:
y.get_weight()

array([[0],
       [1],
       [2]])

In [890]:
y.train(np.array([0.75]))

[1. 0. 1.]


In [873]:
np.array([[1, 1],[1,2]])[(1,1)]

2

In [874]:
np.array([1, 1, 5])[(2,)]

5